version: '3.1'

services:
  database:
    image: mysql:8.0
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: 'Asia/Seoul'
    ports:
      - ${MYSQL_PORT}:3306
    command:
      - --skip-ssl
      - useSSL=false
      - allowPublicKeyRetrieval=true
    networks:
      - lolpee-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: database
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${PMA_PORT}:80
    depends_on:
      - database
    networks:
      - lolpee-network

  cache-database:
    image: redis:6.0
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - lolpee-network

networks:
  lolpee-network:
    driver: bridge